try again

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,24 +16,24 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}; \
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
 
-#   revert-migrations:
-#     description: Revert the last migration if successfully run in the current workflow.
-#     parameters:
-#       # Add parameter here     
-#     steps:
-#       - run:
-#           name: Revert migrations
-#           # Add when this will run
-#           command: |
-#             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-#             SUCCESS = 1
-#             if(( $SUCCESS==1 )); 
-#             then
-#             #  cd ~/project/backend
-#             #  npm install
-#             #  Add revert code here. You can find this in the Getting Started section.
-#               exit 1
-#             fi
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
             
 jobs:
   build-frontend:
@@ -224,6 +224,13 @@ jobs:
       # Checkout code from git
       - checkout
       - run:
+          name: Install Dependencies
+          command: |
+            sudo apt update
+            sudo apt install python3 python3-pip curl
+            pip3 install --upgrade pip
+            pip3 install --no-cache-dir awscli
+      - run:
           name: Run migrations
           command: |
             cd backend
@@ -323,15 +330,34 @@ jobs:
       - run:
           name: Get backend url
           command: |
-            # your code here
+            export BACKEND_IP=${aws ec2 describe-instances \
+                                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                                --output text}
+            export API_URL="http://${BACKEND_IP}:3030"
       - run:
           name: Backend smoke test.
+          # Fetch and prepare the BACKEND_IP env var
           command: |
-            # your code here
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            fi
       # Here's where you will add some code to rollback on failure  
       - destroy-environment:
           workflow_id: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}.udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
